
app:
    greeting: Springboot Config
    version: 2:1
    database: '{  host:"localhost", username:"sezayir", password:"1234"  }'
    environment:
     names: dev,qa,prod
    
mail:
    from: info@sezo.com
    hostname: info@sezo.com
    port: 8091
 
management:
           endpoints:
            web:
              exposure:
                include: "*"