
app:
    greeting: Springboot Config dev from configuration server
    version: 2:1
    environment: names=dev,qa,prod
    database: '{  host:"devhost", username:"sezayir", password:"abc"  }'
    
mail:
    port: 9001
 
