
app:
    greeting: Springboot Config from Config server
    version: 2:1
    database: '{  host:"localhost", username:"sezayir", password:"1234Abc}'
    environment:
     names: dev,qa,prod
    
mail:
    from: info@sezo.com
    hostname: info@sezo.com
    port: 8093
 
management:
           endpoints:
            web:
              exposure:
                include: "*"